---
apiVersion: onepassword.com/v1
type: kubernetes.io/dockerconfigjson
kind: OnePasswordItem
metadata:
  name: registry
  namespace: system
spec:
  itemPath: vaults/${CAPG_REGISTRY_SECRET_VAULT}/items/registry